# Generated by Django 3.0.6 on 2020-05-23 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicklink',
            name='user_public_key',
            field=models.CharField(max_length=42, validators=[django.core.validators.MinLengthValidator(42)], verbose_name='User public key'),
        ),
        migrations.AlterField(
            model_name='salelink',
            name='user_public_key',
            field=models.CharField(max_length=42, validators=[django.core.validators.MinLengthValidator(42)], verbose_name='User public key'),
        ),
    ]
