# Generated by Django 3.0.6 on 2020-05-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_unique_url_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='google_property',
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('user_public_key', 'campaign')},
        ),
        migrations.RemoveField(
            model_name='link',
            name='user',
        ),
    ]
