# Generated by Django 3.0.6 on 2020-05-24 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_add_google_view__user_pk__sale_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickcampaign',
            name='started',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Campaign start date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salecampaign',
            name='started',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Campaign start date'),
            preserve_default=False,
        ),
    ]
