# Generated by Django 3.0.6 on 2020-05-24 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_started_to_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickcampaign',
            name='started',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Campaign start date'),
        ),
        migrations.AlterField(
            model_name='salecampaign',
            name='started',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Campaign start date'),
        ),
    ]
